language: node_js

os:
        - linux
        - osx

node_js:
        - "7"

sudo: false

compiler: clang

addons:
        apt:
                packages:
                        - libglib2.0-dev
                        - libcairo2-dev
                        - libpng-dev
                        - g++-5

before_install:
        - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
        - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install glib cairo libpng; fi
        - if [[ "$CXX" == "g++" ]]; then export CXX="g++-5"; fi
